on: [push]

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: shubham90/gh-pkg-action@v1.13
      with:
        azure-artifacts-feed-url: 'https://dev.azure.com/codesharing-su0/upackTasks'
        azure-devops-org-url: 'https://dev.azure.com/codesharing-su0'
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'

    - name: Install nuget package
      run: nuget install -Source "https://pkgs.dev.azure.com/codesharing-SU0/_packaging/shbhawsiTest1/nuget/v3/index.json" CloudBuild.BuildTools.Client
      shell: cmd
